[package]
name = "pixel-game-lib"
version = "0.8.0"
edition = "2021"
authors = ["Thomas Versteeg <t@versteeg.email>"]
license = "AGPL-3.0"
homepage = "https://github.com/tversteeg/pixel-game-lib"
readme = "README.md"
description = "Utility library for 2D pixel-based games"
documentation = "https://docs.rs/pixel-game-lib"
repository = "https://github.com/tversteeg/pixel-game-lib.git"
keywords = ["gamedev", "utility"]
categories = [
	"games",
	"game-engines",
]
rust-version = "1.74.0"

[features]
default = ["hot-reloading-assets", "physics"]

# Embed a default pixel font.
default-font = []

# Enable assets and hot-reload assets from disk when they are saved.
#
# Has no effect when building for the web.
hot-reloading-assets = ["assets_manager/hot-reloading"]

# Enable assets and include them all in the binary.
#
# Always enabled when building for the web.
#
# This feature takes precedence over `hot-reloading-assets` when both are set.
embedded-assets = ["assets_manager/embedded"]

# Enable the 2D physics engine.
physics = ["dep:hecs", "dep:bvh-arena", "dep:parry2d-f64"]

# Integrate [Yarn Spinner](https://www.yarnspinner.dev/), a friendly DSL for writing dialogue.
dialogue = ["dep:yarnspinner"]

# Allow playing music and sounds using the [Kira](https://docs.rs/kira/latest/kira/) crate.
audio = ["dep:kira"]

[dependencies]
miette = "7.2.0"
vek = "0.16.1"
serde = { version = "1.0.197", features = ["derive"] }
game-loop = { version = "1.1.0", features = ["winit"] }
winit_input_helper = "0.16.0"
wgpu = { version = "0.19.3", default-features = false, features = ["webgl", "wgsl"] }
puffin = "0.19.0"
bytemuck = { version = "1.15.0", features = ["derive"] }
bitvec = "1.0.1"
log = "0.4.21"
hashbrown = "0.14.3"
png = "0.17.13"

# `physics` feature

bvh-arena = { version = "1.1.3", optional = true }
hecs = { version = "0.10.4", optional = true, features = ["macros"] }
parry2d-f64 = { version = "0.13.6", optional = true , features = ["simd-stable"] }

# `dialogue` feature

yarnspinner = { version = "0.2.0", optional = true }

# `audio` feature

kira = { version = "0.8.7", default-features = false, features = ["cpal", "ogg", "serde"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
assets_manager = { version = "0.11.3", default-features = false, features = ["toml", "png", "ahash", "macros"] }

pollster = "0.3.0"
env_logger = "0.11.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
assets_manager = { version = "0.11.3", default-features = false, features = ["toml", "png", "embedded", "macros"] }

web-sys = { version = "0.3.69", features = ["CanvasRenderingContext2d", "Document", "Element", "HtmlCanvasElement", "ImageData", "Window"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
console_error_panic_hook = "0.1.7"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# Show nice output for the examples
miette = { version = "7.2.0", features = ["fancy"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
# Show nice output for the examples
miette = { version = "7.2.0", features = ["fancy-no-syscall"] }

[[example]]
name = "window"

[[example]]
name = "sprite"

[[example]]
name = "audio"
required-features = ["audio"]

[workspace]
members = ["run-wasm"]

# Ensure audio performance is not too poor when running in dev mode
[profile.dev.package]
kira.opt-level = 3
cpal.opt-level = 3
symphonia.opt-level = 3
symphonia-format-ogg.opt-level = 3
symphonia-codec-vorbis.opt-level = 3
