name: CI
on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  # Check for formatting
  rustfmt:
    name: Formatter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # Run a compilation check on Linux, macOS, and Windows
  compile:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      # Checkout the branch being tested
      - uses: actions/checkout@v4

      # Install required libraries
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libasound2-dev

      # Install rust stable
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # Install cargo-hack
      - uses: taiki-e/install-action@cargo-hack

      # Check different feature combinations
      - name: Build (no features)
        run: cargo check --no-default-features
      - name: Build (dialogue)
        run: cargo check --no-default-features --features dialogue
      - name: Build (in-game-profiler)
        run: cargo check --no-default-features --features in-game-profiler
      - name: Build (embed-assets)
        run: cargo check --no-default-features --features embed-assets
      - name: Build (hot-reload-assets)
        run: cargo check --no-default-features --features hot-reload-assets

  # Run tests on Linux
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch being tested
      - uses: actions/checkout@v4

      # Install required libraries
      - name: Install dependencies
        run: sudo apt-get install -y libasound2-dev

      # Install rust stable
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # Test all features on the target platform
      - name: Test
        run: cargo test --features dialogue

  # Build the WASM target & push it to GitHub pages
  wasm:
    name: WASM test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install rust stable
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      # Cache the built dependencies
      - uses: Swatinem/rust-cache@v2.7.3
        with:
          save-if: ${{ github.event_name == 'push' }}

      # Build the WASM 
      - name: Build
        run: cargo run --package run-wasm -- --example sprite --release --no-default-features --features embed-assets --build-only

      # Deploy to GitHub pages
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: target/wasm-examples/sprite
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
